FROM python:3.14-slim AS builder

WORKDIR /app

COPY requirements.txt  .

RUN pip install -r requirements.txt  --target /app/libraries

COPY .  .

FROM gcr.io/distroless/python3-debian13 AS deployer

WORKDIR /app

COPY  --from=builder /app/libraries  /app/libraries

COPY --from=builder /app   .

ENV PYTHONPATH=/app/libraries

EXPOSE 80

ENTRYPOINT ["python" ,"run.py"]
